#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: "macos-latest"

    steps:
      - script: uname -a && git submodule update --init --recursive
        displayName: "Prepare Git submodules"

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            brew install ninja;
            brew info cmake;
        displayName: "Prepare Homebrew packages"

      - script: gradle wrapper
        displayName: "Make Gradlew"

      - task: Gradle@2
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          gradleOptions: ""
          tasks: "assemble"
        displayName: "Gradle Assembe"
