
trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

steps:
- checkout: self  
  fetchDepth: 2
  submodules: true

- script: brew install ninja
  displayName: 'Install Ninja (Brew)'

# Expect CMake 3.14.5
- script: brew info cmake
  displayName: 'Install CMake (Brew)'

- script: gradle wrapper
  displayName: 'Make Gradlew'

- task: Gradle@2 
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-warning-mode all'
    tasks: 'assemble'
